{ config, lib, pkgs, homeDirectory, hostName, ... }:

let
  cfg = config.dotfiles.ssh;
  secretRoot = ../../secrets/hosts;
  publicRoot = ../../secrets/public;
  defaultSecretFile = secretRoot + "/${hostName}.yaml";
  defaultPublicKeyFile = publicRoot + "/${hostName}-id_ed25519.pub";
  hasDefaultSecret = builtins.pathExists defaultSecretFile;
  hasDefaultPublicKey = builtins.pathExists defaultPublicKeyFile;
in
{
  options.dotfiles.ssh = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = hasDefaultSecret && hasDefaultPublicKey;
      description = "Deploy this host's SOPS-encrypted Ed25519 SSH identity.";
    };

    secretFile = lib.mkOption {
      type = lib.types.path;
      default = defaultSecretFile;
      description = "Per-deployment SOPS file containing ssh/id_ed25519.";
    };

    publicKeyFile = lib.mkOption {
      type = lib.types.path;
      default = defaultPublicKeyFile;
      description = "Per-deployment public Ed25519 key.";
    };

    ageKeyFile = lib.mkOption {
      type = lib.types.str;
      default = "${homeDirectory}/.config/sops/age/keys.txt";
      description = "Host-local age identity used to decrypt this deployment's SOPS file.";
    };

    manageAuthorizedKeys = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Explicitly opt in to managing incoming SSH authorization.";
    };

    authorizedKeys = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Public keys allowed for incoming SSH connections.";
    };
  };

  config = lib.mkMerge [
    {
      assertions = [
        {
          assertion = !cfg.enable || builtins.pathExists cfg.secretFile;
          message = "dotfiles.ssh.secretFile does not exist for ${hostName}. Run: nix run .#bootstrap-ssh -- ${hostName}";
        }
        {
          assertion = !cfg.enable || builtins.pathExists cfg.publicKeyFile;
          message = "dotfiles.ssh.publicKeyFile does not exist for ${hostName}. Run: nix run .#bootstrap-ssh -- ${hostName}";
        }
        {
          assertion = !cfg.manageAuthorizedKeys || cfg.authorizedKeys != [ ];
          message = "dotfiles.ssh.authorizedKeys must be non-empty when manageAuthorizedKeys is enabled.";
        }
      ];
    }

    (lib.mkIf cfg.enable {
      sops.defaultSopsFile = cfg.secretFile;
      sops.age.keyFile = cfg.ageKeyFile;
      sops.secrets."ssh/id_ed25519" = {
        path = "${homeDirectory}/.ssh/id_ed25519";
        mode = "0600";
      };

      home.file.".ssh/id_ed25519.pub".source = cfg.publicKeyFile;

      home.file.".ssh/config.d/90-dotfiles-github.conf".text = ''
        # Generated by Home Manager for ${hostName}.
        Host github.com
          HostName github.com
          User git
          IdentityFile ~/.ssh/id_ed25519
          IdentitiesOnly yes
          AddKeysToAgent yes
      '';

      home.activation.dotfilesSshPermissions = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        $DRY_RUN_CMD mkdir -p "$HOME/.ssh"
        $DRY_RUN_CMD chmod 700 "$HOME/.ssh"
        $DRY_RUN_CMD chmod 600 "$HOME/.ssh/id_ed25519"
        $DRY_RUN_CMD chmod 644 "$HOME/.ssh/id_ed25519.pub"
      '';
    })

    (lib.mkIf cfg.manageAuthorizedKeys {
      home.file.".ssh/authorized_keys".text = "${lib.concatStringsSep "\n" cfg.authorizedKeys}\n";
      home.activation.dotfilesAuthorizedKeysMode = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        $DRY_RUN_CMD chmod 600 "$HOME/.ssh/authorized_keys"
      '';
    })
  ];
}
