# Fish-to-zsh compatibility layer. Keep functions small and POSIX-friendly so
# the same profile works in Crostini, Debian Trixie containers, and macOS.

# fnm provides shell hooks only when installed and available on this host.
if (( $+commands[fnm] )); then
  eval "$(fnm env --use-on-cd --shell zsh)"
fi

# Bun's completion script is generated by the installed Bun binary.
if (( $+commands[bun] )); then
  eval "$(bun completions 2>/dev/null)"
fi

# Keep the prompt and fzf integrations lazy enough for non-interactive shells.
if [[ -o interactive ]]; then
  if (( $+commands[fzf] )); then
    source <(fzf --zsh 2>/dev/null)
  fi

  # Alt-Up mirrors Fish's directory navigation binding.
  bindkey -s '\e[1;3A' 'cd ..\n'
  bindkey '^F' autosuggest-accept
fi

backup() {
  if (( $# != 1 )); then
    print -u2 "usage: backup FILE|DIRECTORY"
    return 2
  fi
  local target=$1 timestamp backup_path
  if [[ ! -e $target ]]; then
    print -u2 "File or directory '$target' does not exist."
    return 1
  fi
  timestamp=$(date +%Y%m%d_%H%M%S)
  backup_path="${target}_${timestamp}.bak"
  cp -riv -- "$target" "$backup_path"
  print "Created backup: $backup_path"
}

extract() {
  if (( $# != 1 )); then
    print -u2 "usage: extract ARCHIVE"
    return 2
  fi
  local archive=$1
  [[ -f $archive ]] || { print -u2 "Error: '$archive' is not a valid file."; return 1; }
  case $archive in
    *.tar.gz|*.tgz) tar xzf -- "$archive" ;;
    *.tar.bz2|*.tbz2) tar xjf -- "$archive" ;;
    *.tar.xz|*.txz) tar xJf -- "$archive" ;;
    *.tar) tar xf -- "$archive" ;;
    *.zip) unzip -- "$archive" ;;
    *.rar) unrar x -- "$archive" ;;
    *.7z) 7z x -- "$archive" ;;
    *.gz) gunzip -- "$archive" ;;
    *) print -u2 "Error: '$archive' cannot be extracted."; return 1 ;;
  esac
}

mkcd() {
  if (( $# != 1 )); then
    print -u2 "usage: mkcd DIRECTORY"
    return 2
  fi
  mkdir -p -- "$1" && builtin cd -- "$1"
}

rfv() {
  local selection file line
  selection=$(rg --color=always --line-number --no-heading --smart-case "$@" |
    fzf --ansi --preview 'bat --color=always --highlight-line {2} {1}' \
      --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' |
    awk -F: '{print $1 ":" $2}') || return
  [[ -n $selection ]] || return
  file=${selection%%:*}
  line=${selection#*:}
  micro "$file" +"$line"
}

# Codex is optional in nixpkgs. Keep the command usable through the published
# npm package when the host only has Node.js/npm and cannot install a global
# CLI package.
if (( ! $+commands[codex] && $+commands[npx] )); then
  codex() {
    command npx --yes @openai/codex "$@"
  }
fi

# Keep a useful shell completion for the locally installed agy CLI. The
# generated Fish completion remains the source of truth for future expansion.
if (( $+commands[agy] )); then
  compdef '_arguments \
    "(-c --continue)"{-c,--continue}' \
    "--add-dir=[directory]:directory:_directories" \
    "--conversation=[conversation id]" \
    "--dangerously-skip-permissions" \
    "(-i --prompt-interactive)"{-i,--prompt-interactive} \
    "--log-file=[path]:file:_files" \
    "--model=[model]" \
    "(-p --print --prompt)"{-p,--print,--prompt} \
    "--print-timeout=[seconds]" \
    "--sandbox" \
    "1:subcommand:(changelog help install models plugin plugins update)"' agy
fi
