{
  config,
  lib,
  homeDirectory,
  hostName,
  username,
  ...
}:

let
  cfg = config.dotfiles.secrets;
  manifest = import ../../../secrets/manifest.nix;
  publicRoot = ../../../secrets/public;
  sshDeployments = lib.filterAttrs (_: deployment: deployment.ssh or false) manifest.deployments;

  readPublicKey =
    name:
    let
      file = publicRoot + "/${name}-id_ed25519.pub";
    in
    if builtins.pathExists file then lib.removeSuffix "\n" (builtins.readFile file) else null;

  peerHostBlocks = lib.concatStrings (
    lib.mapAttrsToList (
      name: peer:
      let
        publicKey = readPublicKey name;
        peerHostName = peer.sshHostName or name;
        aliases = peer.sshAliases or [ ];
        hostPatterns = lib.concatStringsSep " " (
          [
            name
            peerHostName
          ]
          ++ aliases
        );
      in
      if name == hostName || publicKey == null then
        ""
      else
        ''
          Host ${hostPatterns}
            HostName ${peerHostName}
            User ${username}
            IdentityFile ~/.ssh/id_ed25519
            IdentitiesOnly yes
            AddKeysToAgent yes
        ''
    ) sshDeployments
  );

  enabled = cfg.enable && cfg.ssh.enable;
in
{
  config = lib.mkMerge [
    {
      assertions = [
        {
          assertion = !enabled || builtins.pathExists cfg.secretFile;
          message = "dotfiles.secrets.secretFile does not exist for ${hostName}. Run: nix run .#bootstrap-secrets -- ssh ${hostName}";
        }
        {
          assertion = !enabled || builtins.pathExists cfg.ssh.publicKeyFile;
          message = "dotfiles.secrets.ssh.publicKeyFile does not exist for ${hostName}. Run: nix run .#bootstrap-secrets -- ssh ${hostName}";
        }
        {
          assertion = !cfg.ssh.manageAuthorizedKeys || cfg.ssh.authorizedKeys != [ ];
          message = "dotfiles.secrets.ssh.authorizedKeys must be non-empty when manageAuthorizedKeys is enabled.";
        }
      ];
    }

    (lib.mkIf enabled {
      sops.secrets."ssh/id_ed25519" = {
        path = "${homeDirectory}/.ssh/id_ed25519";
        mode = "0600";
      };

      home.file.".ssh/id_ed25519.pub".source = cfg.ssh.publicKeyFile;

      home.file.".ssh/config.d/90-dotfiles-github.conf".text = ''
        # Generated by Home Manager for ${hostName}.
        Host github.com
          HostName github.com
          User git
          IdentityFile ~/.ssh/id_ed25519
          IdentitiesOnly yes
          AddKeysToAgent yes
      '';

      home.file.".ssh/config.d/90-dotfiles-peers.conf" = lib.mkIf (peerHostBlocks != "") {
        text = ''
          # Generated by Home Manager for ${hostName}.
          # Peer hosts from secrets/manifest.nix + secrets/public/*.pub
          ${peerHostBlocks}
        '';
      };

      # After sops-nix (the Darwin override installs secrets synchronously).
      # Do not chmod HM-managed *.pub / authorized_keys: they are Nix-store
      # symlinks. The private key is a real sops-install-secrets file.
      home.activation.dotfilesSshPermissions = lib.hm.dag.entryAfter [ "writeBoundary" "sops-nix" ] ''
        $DRY_RUN_CMD mkdir -p "$HOME/.ssh" "$HOME/.ssh/config.d"
        $DRY_RUN_CMD chmod 700 "$HOME/.ssh"
        if [[ -f "$HOME/.ssh/id_ed25519" && ! -L "$HOME/.ssh/id_ed25519" ]]; then
          $DRY_RUN_CMD chmod 600 "$HOME/.ssh/id_ed25519"
        fi

        if [[ ! -e "$HOME/.ssh/config" ]]; then
          $DRY_RUN_CMD printf '%s\n' 'Include ~/.ssh/config.d/*.conf' >"$HOME/.ssh/config"
          $DRY_RUN_CMD chmod 600 "$HOME/.ssh/config"
        elif ! grep -Eq '^[[:space:]]*Include[[:space:]]+(~/|\$HOME/)?\.ssh/config\.d/' "$HOME/.ssh/config"; then
          $DRY_RUN_CMD printf '%s\n%s\n' 'Include ~/.ssh/config.d/*.conf' "$(cat "$HOME/.ssh/config")" >"$HOME/.ssh/config"
          $DRY_RUN_CMD chmod 600 "$HOME/.ssh/config"
        fi
      '';
    })

    (lib.mkIf (cfg.enable && cfg.ssh.manageAuthorizedKeys) {
      # Keep force until the preserving ~/.ssh Stow migration has run on every
      # SSH-enabled host; stale plaintext files and backups otherwise block HM.
      home.file.".ssh/authorized_keys" = {
        force = true;
        text = "${lib.concatStringsSep "\n" cfg.ssh.authorizedKeys}\n";
      };
    })
  ];
}
