{ config, lib, pkgs, username, homeDirectory, stateVersion, hostName, ... }:

let
  cfg = config.dotfiles.darwin;
in
{
  options.dotfiles.darwin = {
    proxyBridgePackage = lib.mkOption {
      type = lib.types.str;
      default = "proxybridge (Homebrew cask)";
      description = "ProxyBridge install path; managed by nix-darwin Homebrew.";
    };

    ssh = {
      configInclude = lib.mkOption {
        type = lib.types.str;
        default = "Include ~/.ssh/config.d/*.conf";
        description = "Include declaration to add to the user's main SSH config.";
      };
    };
  };

  config = {
    # Host-specific SSH client hints. Private keys come from dotfiles.secrets.
    home.file.".ssh/config.d/90-dotfiles-mini.conf" = lib.mkIf (hostName == "mini") {
      text = ''
        # Generated by Home Manager for ${hostName}.
        # Add `${cfg.ssh.configInclude}` to ~/.ssh/config once to load this file.
        Host macmini mini mini.local
          HostName mini.local
          User ${username}
          IdentityFile ~/.ssh/id_ed25519
          IdentitiesOnly yes
      '';
    };

    home.file.".config/launchagents-templates/ai.agentcli.litellm.plist".source = ../../templates/launchagents/ai.agentcli.litellm.plist;
    home.file.".config/launchagents-templates/com.esko.llama-server.plist".source = ../../templates/launchagents/com.esko.llama-server.plist;
    home.file.".config/proxybridge/ProxyBridge.defaults.json".source = ../../templates/proxybridge/ProxyBridge.defaults.json;
    home.file.".config/proxybridge/README.md".source = ../../templates/proxybridge/README.md;
  };
}

