{ config, lib, pkgs, username, homeDirectory, stateVersion, hostName, ... }:

let
  cfg = config.dotfiles.darwin;
  sshCfg = cfg.ssh;
in
{
  options.dotfiles.darwin = {
    proxyBridgePackage = lib.mkOption {
      type = lib.types.str;
      default = "ProxyBridge v3.2.0 (upstream signed universal pkg)";
      description = "Documented install intent; this package is never fetched or installed by Home Manager.";
    };

    ssh = {
      enable = lib.mkEnableOption "the encrypted per-host Ed25519 SSH key";

      privateKeySecret = lib.mkOption {
        type = lib.types.str;
        default = "ssh/mini/id_ed25519";
        description = "sops-nix secret name containing the Mini's Ed25519 private key.";
      };

      publicKey = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Optional public key text written to ~/.ssh/id_ed25519.pub.";
      };

      manageAuthorizedKeys = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Explicitly opt in to managing ~/.ssh/authorized_keys.";
      };

      authorizedKeys = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        description = "Public keys allowed for incoming SSH; empty by default.";
      };

      configInclude = lib.mkOption {
        type = lib.types.str;
        default = "Include ~/.ssh/config.d/*.conf";
        description = "Include declaration to add to the user's main SSH config.";
      };
    };
  };

  config = {
    assertions = [
      {
        assertion = !sshCfg.manageAuthorizedKeys || sshCfg.authorizedKeys != [ ];
        message = "dotfiles.darwin.ssh.authorizedKeys must be non-empty when manageAuthorizedKeys is enabled.";
      }
    ];

    # Keep the declaration available for review without replacing an existing
    # hand-maintained ~/.ssh/config. The existing config can include this file.
    home.file.".ssh/config.d/90-dotfiles-mini.conf" = {
      text = ''
        # Generated by Home Manager for ${hostName}.
        # Add `${sshCfg.configInclude}` to ~/.ssh/config once to load this file.
        Host mini mini.local
          HostName mini.local
          User ${username}
          IdentityFile ~/.ssh/id_ed25519
          IdentitiesOnly yes
      '';
      mode = "0600";
    };

    home.file.".ssh/id_ed25519.pub" = lib.mkIf (sshCfg.publicKey != null) {
      text = "${sshCfg.publicKey}\n";
      mode = "0644";
    };

    home.file.".ssh/authorized_keys" = lib.mkIf sshCfg.manageAuthorizedKeys {
      text = "${lib.concatStringsSep "\n" sshCfg.authorizedKeys}\n";
      mode = "0600";
    };

    # This is an opt-in secret interface only. No encrypted file is committed
    # by the module and no private key is generated when it is disabled.
    sops.secrets = lib.mkIf sshCfg.enable {
      "${sshCfg.privateKeySecret}" = {
        path = "${homeDirectory}/.ssh/id_ed25519";
        mode = "0600";
      };
    };

    # Templates are rendered into a reviewable directory but never registered
    # with launchd. Disabled=true is defense in depth for manual installation.
    home.file.".config/launchagents-templates/ai.agentcli.litellm.plist".source = ../../templates/launchagents/ai.agentcli.litellm.plist;
    home.file.".config/launchagents-templates/com.esko.llama-server.plist".source = ../../templates/launchagents/com.esko.llama-server.plist;
    home.file.".config/proxybridge/ProxyBridge.defaults.json".source = ../../templates/proxybridge/ProxyBridge.defaults.json;
    home.file.".config/proxybridge/README.md".source = ../../templates/proxybridge/README.md;
  };
}
