#!/usr/bin/env bash
# Shared helpers for SOPS bootstrap and render scripts.

# shellcheck source=manifest-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/manifest-common.sh"

sops_repo_root() {
  git -C "${SOPS_REPO_ROOT:-$PWD}" rev-parse --show-toplevel 2>/dev/null \
    || printf '%s\n' "${SOPS_REPO_ROOT:?Set SOPS_REPO_ROOT when not in a git repo}"
}

sops_age_key_file() {
  printf '%s\n' "${SOPS_AGE_KEY_FILE:-$HOME/.config/sops/age/keys.txt}"
}

sops_ensure_age_identity() {
  local age_key_file recipient
  age_key_file=$(sops_age_key_file)

  mkdir -p "$(dirname "$age_key_file")"
  chmod 700 "$(dirname "$age_key_file")"

  if [[ ! -f "$age_key_file" ]]; then
    # Status must go to stderr: callers capture stdout as the age recipient.
    printf 'Creating the local age identity at %s\n' "$age_key_file" >&2
    age-keygen -o "$age_key_file"
    chmod 600 "$age_key_file"
  fi

  recipient=$(age-keygen -y "$age_key_file")
  recipient=$(printf '%s' "$recipient" | tr -d '[:space:]')
  if [[ -z "$recipient" || "$recipient" != age1* ]]; then
    printf 'Could not derive an age recipient from %s\n' "$age_key_file" >&2
    return 1
  fi
  printf '%s\n' "$recipient"
}

sops_render_config() {
  local repo_root recipient_dir path host host_regex host_recipient
  repo_root=$(sops_repo_root)
  recipient_dir="$repo_root/secrets/age-recipients"

  printf '%s\n' '# Generated by bootstrap-secrets; age private identities stay outside Git.'
  printf '%s\n' 'creation_rules:'

  shopt -s nullglob
  for path in "$recipient_dir"/*.txt; do
    host=$(basename "$path" .txt)
    host_regex=${host//./\\.}
    host_recipient=$(tr -d '[:space:]' <"$path")
    [[ "$host_recipient" == age1* ]] || continue
    printf '  - path_regex: ^secrets/hosts/%s\\.yaml$\n' "$host_regex"
    printf '%s\n' '    age:'
    printf '      - %s\n' "$host_recipient"
  done

  printf '%s\n' '  - path_regex: ^secrets/shared\.yaml$'
  printf '%s\n' '    age:'
  for path in "$recipient_dir"/*.txt; do
    host_recipient=$(tr -d '[:space:]' <"$path")
    [[ "$host_recipient" == age1* ]] || continue
    printf '      - %s\n' "$host_recipient"
  done
}

sops_write_config() {
  local repo_root sops_config
  repo_root=$(sops_repo_root)
  sops_config="$repo_root/.sops.yaml"
  sops_render_config >"$sops_config"
  chmod 644 "$sops_config"
}

sops_ensure_recipient() {
  local deployment recipient repo_root recipient_file recipient_dir
  deployment=$1
  repo_root=$(sops_repo_root)
  recipient_dir="$repo_root/secrets/age-recipients"
  recipient_file="$recipient_dir/$deployment.txt"

  recipient=$(sops_ensure_age_identity) || return 1
  if [[ "$recipient" != age1* ]]; then
    printf 'Refusing to write invalid age recipient for %s\n' "$deployment" >&2
    return 1
  fi
  mkdir -p "$recipient_dir"
  printf '%s\n' "$recipient" >"$recipient_file"
  chmod 644 "$recipient_file"
  sops_write_config
  printf '%s\n' "$recipient"
}

sops_secret_file() {
  local deployment repo_root
  deployment=$1
  repo_root=$(sops_repo_root)
  printf '%s\n' "$repo_root/secrets/hosts/$deployment.yaml"
}

sops_secret_file_rel() {
  local deployment=$1
  printf 'secrets/hosts/%s.yaml\n' "$deployment"
}

sops_shared_secret_file() {
  local repo_root
  repo_root=$(sops_repo_root)
  printf '%s\n' "$repo_root/secrets/shared.yaml"
}

sops_shared_secret_file_rel() {
  printf '%s\n' 'secrets/shared.yaml'
}

# Encrypt a plaintext YAML tempfile using creation rules for the repo-relative
# destination. Without --filename-override, sops matches /tmp paths and fails
# with "no matching creation rules found".
sops_encrypt_yaml_file() {
  local filename_override=$1 age_recipients=$2 plain_file=$3 output_file=$4

  sops --encrypt \
    --age "$age_recipients" \
    --filename-override "$filename_override" \
    --input-type yaml \
    --output-type yaml \
    "$plain_file" >"$output_file"
  chmod 600 "$output_file"
}

sops_all_age_recipients() {
  local repo_root recipient_dir path host_recipient
  repo_root=$(sops_repo_root)
  recipient_dir="$repo_root/secrets/age-recipients"

  shopt -s nullglob
  for path in "$recipient_dir"/*.txt; do
    host_recipient=$(tr -d '[:space:]' <"$path")
    [[ -n "$host_recipient" ]] || continue
    printf '%s\n' "$host_recipient"
  done
}

sops_age_recipients_csv() {
  local recipients="" recipient
  while IFS= read -r recipient; do
    [[ -n "$recipient" ]] || continue
    if [[ -n "$recipients" ]]; then
      recipients+=","
    fi
    recipients+="$recipient"
  done < <(sops_all_age_recipients)
  printf '%s' "$recipients"
}

sops_validate_deployment_name() {
  local deployment=$1
  if [[ ! "$deployment" =~ ^[a-z0-9][a-z0-9._-]*$ ]]; then
    printf '%s\n' \
      'Deployment names may contain lowercase letters, digits, dots, underscores, and hyphens.' \
      >&2
    return 1
  fi
}

sops_env_runtime_variable() {
  local env_key=$1
  manifest_eval_raw ".#secretsManifest.envKeys.${env_key}.runtime" \
    || manifest_eval_raw ".#secretsManifest.envKeys.${env_key}"
}

sops_load_env_secret() {
  local deployment=$1 env_key=$2
  local runtime_var value

  runtime_var=$(sops_env_runtime_variable "$env_key")
  if [[ -n "${!runtime_var:-}" ]]; then
    printf '%s' "${!runtime_var}"
    return 0
  fi

  if value=$(sops_decrypt_env_secret "$deployment" "$env_key"); then
    printf '%s' "$value"
    return 0
  fi

  if manifest_env_key_shared "$env_key" && value=$(sops_decrypt_shared_env_secret "$env_key"); then
    printf '%s' "$value"
    return 0
  fi

  return 1
}

sops_env_secret_present_in_file() {
  local secret_file=$1 env_key=$2 value
  [[ -f "$secret_file" ]] || return 1
  command -v sops >/dev/null 2>&1 || return 1
  value=$(sops -d --extract "[\"env\"][\"$env_key\"]" "$secret_file" 2>/dev/null || true)
  [[ -n "$value" ]]
}

sops_env_secret_present() {
  local deployment=$1 env_key=$2
  sops_env_secret_present_in_file "$(sops_secret_file "$deployment")" "$env_key" \
    || {
      manifest_env_key_shared "$env_key" \
        && sops_env_secret_present_in_file "$(sops_shared_secret_file)" "$env_key"
    }
}

sops_decrypt_env_secret() {
  local deployment=$1 env_key=$2 secret_file value

  secret_file=$(sops_secret_file "$deployment")
  sops_env_secret_present_in_file "$secret_file" "$env_key" || return 1
  value=$(sops -d --extract "[\"env\"][\"$env_key\"]" "$secret_file")
  printf '%s' "$value"
}

sops_decrypt_shared_env_secret() {
  local env_key=$1 secret_file value

  secret_file=$(sops_shared_secret_file)
  sops_env_secret_present_in_file "$secret_file" "$env_key" || return 1
  value=$(sops -d --extract "[\"env\"][\"$env_key\"]" "$secret_file")
  printf '%s' "$value"
}

sops_resolve_env_value() {
  local env_key=$1
  local runtime_var dotfiles_var override value

  for override in "${SOPS_ENV_OVERRIDES[@]:-}"; do
    if [[ "$override" == "${env_key}="* ]]; then
      printf '%s' "${override#${env_key}=}"
      return 0
    fi
  done

  if manifest_env_key_shared "$env_key" && value=$(sops_decrypt_shared_env_secret "$env_key"); then
    printf '%s' "$value"
    return 0
  fi

  dotfiles_var="DOTFILES_ENV_${env_key}"
  if [[ -n "${!dotfiles_var:-}" ]]; then
    printf '%s' "${!dotfiles_var}"
    return 0
  fi

  runtime_var=$(sops_env_runtime_variable "$env_key")
  if [[ -n "${!runtime_var:-}" ]]; then
    printf '%s' "${!runtime_var}"
    return 0
  fi

  if [[ -t 0 ]]; then
    printf '%s (%s): ' "$env_key" "$runtime_var"
    IFS= read -r value
  elif [[ -r /dev/tty ]]; then
    printf '%s (%s): ' "$env_key" "$runtime_var" >/dev/tty
    IFS= read -r value </dev/tty
  else
    printf '%s\n' "No value for env.$env_key; set ${runtime_var} or DOTFILES_ENV_${env_key}" >&2
    return 1
  fi

  if [[ -z "$value" ]]; then
    printf '%s\n' "An environment secret value is required for env.$env_key." >&2
    return 1
  fi

  printf '%s' "$value"
}

sops_upsert_shared_env_secret() {
  local env_key=$1 env_value=$2
  local repo_root secret_file recipients tmp_dir plain_secret

  repo_root=$(sops_repo_root)
  secret_file=$(sops_shared_secret_file)
  recipients=$(sops_age_recipients_csv)
  if [[ -z "$recipients" ]]; then
    printf '%s\n' 'At least one age recipient is required for secrets/shared.yaml.' >&2
    return 1
  fi

  sops_write_config

  if [[ -f "$secret_file" ]]; then
    sops --set "[\"env\"][\"$env_key\"] \"$env_value\"" "$secret_file"
  else
    tmp_dir=$(mktemp -d)
    cleanup() {
      rm -rf "$tmp_dir"
    }
    trap cleanup RETURN

    plain_secret="$tmp_dir/shared.yaml"
    {
      printf '%s\n' 'env:'
      printf '  %s: %s\n' "$env_key" "$env_value"
    } >"$plain_secret"

    sops_encrypt_yaml_file "$(sops_shared_secret_file_rel)" "$recipients" \
      "$plain_secret" "$secret_file"
  fi
}

sops_upsert_env_secret() {
  local deployment=$1 env_key=$2 env_value=$3
  local repo_root secret_file recipient tmp_dir plain_secret

  repo_root=$(sops_repo_root)
  secret_file=$(sops_secret_file "$deployment")
  recipient=$(sops_ensure_recipient "$deployment")

  if [[ -f "$secret_file" ]]; then
    sops --set "[\"env\"][\"$env_key\"] \"$env_value\"" "$secret_file"
  else
    tmp_dir=$(mktemp -d)
    cleanup() {
      rm -rf "$tmp_dir"
    }
    trap cleanup RETURN

    plain_secret="$tmp_dir/$deployment.yaml"
    {
      printf '%s\n' 'env:'
      printf '  %s: %s\n' "$env_key" "$env_value"
    } >"$plain_secret"

    sops_encrypt_yaml_file "$(sops_secret_file_rel "$deployment")" "$recipient" \
      "$plain_secret" "$secret_file"
  fi
}

sops_stage_shared_secrets() {
  local repo_root secret_file

  repo_root=$(sops_repo_root)
  secret_file=$(sops_shared_secret_file)

  if ! git -C "$repo_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    return 0
  fi

  git -C "$repo_root" add \
    "$repo_root/.sops.yaml" \
    "$repo_root/secrets/age-recipients" \
    "$secret_file"
}

sops_stage_deployment_secrets() {
  local deployment=$1
  local repo_root secret_file recipient_file

  repo_root=$(sops_repo_root)
  secret_file=$(sops_secret_file "$deployment")
  recipient_file="$repo_root/secrets/age-recipients/$deployment.txt"

  if ! git -C "$repo_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    return 0
  fi

  git -C "$repo_root" add \
    "$repo_root/.sops.yaml" \
    "$recipient_file" \
    "$secret_file"
}
