#!/usr/bin/env bash
set -euo pipefail

umask 077
export LC_ALL=C

usage() {
  cat <<'EOF'
Usage: bootstrap-ssh DEPLOYMENT [--github] [--set-origin-ssh]

Create a per-deployment Ed25519 key, encrypt it with the deployment's local age
identity, and stage only encrypted/public material in the dotfiles repository.

Examples:
  bootstrap-ssh baguette --github --set-origin-ssh
  bootstrap-ssh crostini --github
  bootstrap-ssh mini --github

Options:
  --github         Add the generated public key to the authenticated GitHub account.
  --set-origin-ssh Change this repository's GitHub origin from HTTPS to SSH.
  -h, --help       Show this help.
EOF
}

deployment=""
add_github=false
set_origin_ssh=false

while (($#)); do
  case "$1" in
    --github)
      add_github=true
      ;;
    --set-origin-ssh)
      set_origin_ssh=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -* )
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [[ -n "$deployment" ]]; then
        printf '%s\n' "Only one deployment name may be supplied." >&2
        exit 2
      fi
      deployment=$1
      ;;
  esac
  shift
done

if [[ -z "$deployment" ]]; then
  usage >&2
  exit 2
fi

if [[ ! "$deployment" =~ ^[a-z0-9][a-z0-9._-]*$ ]]; then
  printf '%s\n' "Deployment names may contain lowercase letters, digits, dots, underscores, and hyphens." >&2
  exit 2
fi

repo_root=$(git rev-parse --show-toplevel 2>/dev/null || true)
if [[ -z "$repo_root" ]]; then
  printf '%s\n' "Run this command from the dotfiles repository." >&2
  exit 1
fi

cd "$repo_root"

age_key_file=${SOPS_AGE_KEY_FILE:-$HOME/.config/sops/age/keys.txt}
recipient_dir="$repo_root/secrets/age-recipients"
host_secret_dir="$repo_root/secrets/hosts"
public_dir="$repo_root/secrets/public"
recipient_file="$recipient_dir/$deployment.txt"
secret_file="$host_secret_dir/$deployment.yaml"
public_key_file="$public_dir/${deployment}-id_ed25519.pub"
sops_config="$repo_root/.sops.yaml"

if [[ -e "$secret_file" || -e "$public_key_file" || -e "$recipient_file" ]]; then
  printf '%s\n' "SSH material for '$deployment' already exists; refusing to overwrite it." >&2
  exit 1
fi

mkdir -p "$(dirname "$age_key_file")" "$recipient_dir" "$host_secret_dir" "$public_dir"
chmod 700 "$(dirname "$age_key_file")"

if [[ ! -f "$age_key_file" ]]; then
  printf 'Creating the local age identity at %s\n' "$age_key_file"
  age-keygen -o "$age_key_file"
  chmod 600 "$age_key_file"
fi

recipient=$(age-keygen -y "$age_key_file")
if [[ -z "$recipient" ]]; then
  printf 'Could not derive an age recipient from %s\n' "$age_key_file" >&2
  exit 1
fi

printf '%s\n' "$recipient" > "$recipient_file"
chmod 644 "$recipient_file"

render_sops_config() {
  printf '%s\n' '# Generated by nix run .#bootstrap-ssh; age private identities stay outside Git.'
  printf '%s\n' 'creation_rules:'

  local path host host_regex host_recipient
  shopt -s nullglob
  for path in "$recipient_dir"/*.txt; do
    host=$(basename "$path" .txt)
    host_regex=${host//./\\.}
    host_recipient=$(tr -d '[:space:]' < "$path")
    printf '  - path_regex: ^secrets/hosts/%s\\.yaml$\n' "$host_regex"
    printf '%s\n' '    age:'
    printf '      - %s\n' "$host_recipient"
  done
}

render_sops_config > "$sops_config"
chmod 644 "$sops_config"

tmp_dir=$(mktemp -d)
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT HUP INT TERM

private_key="$tmp_dir/id_ed25519"
plain_secret="$tmp_dir/$deployment.yaml"

printf '%s\n' "Generating the $deployment Ed25519 key. Set a passphrase when prompted."
ssh-keygen -t ed25519 -a 100 -C "esko@$deployment" -f "$private_key"

cp "$private_key.pub" "$public_key_file"
chmod 644 "$public_key_file"

{
  printf '%s\n' 'ssh:'
  printf '%s\n' '  id_ed25519: |-'
  sed 's/^/    /' "$private_key"
} > "$plain_secret"

sops --encrypt \
  --age "$recipient" \
  --input-type yaml \
  --output-type yaml \
  "$plain_secret" > "$secret_file"
chmod 600 "$secret_file"

git add "$sops_config" "$recipient_file" "$secret_file" "$public_key_file"

if "$add_github"; then
  if ! gh auth status --hostname github.com >/dev/null 2>&1; then
    gh auth login --hostname github.com --git-protocol ssh
  fi
  gh ssh-key add "$public_key_file" --title "$deployment-$(date +%Y-%m-%d)"
fi

if "$set_origin_ssh"; then
  origin_url=$(git remote get-url origin 2>/dev/null || true)
  case "$origin_url" in
    https://github.com/*)
      repository=${origin_url#https://github.com/}
      repository=${repository%.git}
      git remote set-url origin "git@github.com:${repository}.git"
      ;;
    git@github.com:*)
      ;;
    *)
      printf 'Origin is not a GitHub HTTPS remote; leaving it unchanged: %s\n' "$origin_url" >&2
      ;;
  esac
fi

cat <<EOF

Created Nix/SOPS-managed SSH material for: $deployment

Encrypted host secrets: $secret_file
Public SSH key:        $public_key_file
Public age recipient:  $recipient_file
Local age identity:    $age_key_file

Back up the local age identity securely. Do not commit or upload it.
The generated files are staged but not committed. Review them with:
  git status --short
  git diff --cached --stat

After committing, activate the matching deployment normally. The shared Home
Manager module will detect secrets/hosts/$deployment.yaml and deploy the key to
~/.ssh/id_ed25519.
EOF
